services:
  - type: worker        # ✅ ВАЖНО: worker, а не web!
    name: reactbot
    env: node
    buildCommand: npm install
    startCommand: node bot/index.js
    envVars:
      - key: NODE_ENV
        value: production
